apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sample
spec:
  schedule: '* * * * *'
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: sample
        spec:
          initContainers:
          - name: init-foo
            image: busybox:1.31.1
          - name: init-bar
            image: busybox:1.31.1
          containers:
          - name: sample-foo
            image: busybox:1.31.1
            resources:
              limits:
                cpu: 200m
                memory: 100Mi
              requests:
                cpu: 50m
                memory: 100Mi
          - name: sample-bar
            image: busybox:1.31.1
            resources:
              limits:
                cpu: 200m
                memory: 100Mi
              requests:
                cpu: 50m
                memory: 100Mi
