---
apiVersion: v1
kind: Secret
metadata:
  name: sample-1
data:
  MY_SECRET: one_little_duck
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: sample-2
data:
  MY_SECRET: two_little_duck
type: Opaque
