---
apiVersion: v1
kind: Secret
metadata:
  name: sample-secret
data:
  MY_SECRET: one_little_duck
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: sample-secret-2
data:
  MY_SECRET: two_little_duck
type: Opaque
